// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJaCUzu9U1gHkIcCUwWRRha2vk99uFufo',
    appId: '1:578813582074:android:8d35f81b7d6fbc54bc0743',
    messagingSenderId: '578813582074',
    projectId: 'smart-wastebin-6ca5b',
    databaseURL: 'https://smart-wastebin-6ca5b-default-rtdb.firebaseio.com',
    storageBucket: 'smart-wastebin-6ca5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU6Z9hFiQBHfkUJbHlyAoLmn-ZPyfKhBE',
    appId: '1:578813582074:ios:d56739d6bdf0dcd5bc0743',
    messagingSenderId: '578813582074',
    projectId: 'smart-wastebin-6ca5b',
    databaseURL: 'https://smart-wastebin-6ca5b-default-rtdb.firebaseio.com',
    storageBucket: 'smart-wastebin-6ca5b.firebasestorage.app',
    iosBundleId: 'com.example.keepNigeriaClean',
  );

}